version: '3'
services:
  db:
    image: rpsacr2.azurecr.io/db
    build: db
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    expose:
    - 5432:5432
    ports:
    - 5432:5432
    restart: always
  app:
    build: server/rpsjpa
    image: rpsacr2.azurecr.io/app
    container_name: app
    expose:
    - 8080:8080
    ports:
    - 8080:8080
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    depends_on:
    - db
  ui: 
    build: client/rpsui
    image: rpsacr2.azurecr.io/ui
    container_name: ui
    ports:
    - 80:80
    depends_on:
    - app
