services:
  db:
    image: postgres
    build: db
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    expose:
    - 5432:5432
    ports:
    - 5432:5432
    restart: always
  app:
    build: server/rpsjpa
    expose:
    - 8080:8080
    ports:
    - 8080:8080
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=password
    depends_on:
    - db
  ui: 
    build: client/rpsui
    ports:
    - 3000:3000
    depends_on:
    - app

